// [answer, requested clue, Sakura's association, Kakashi's sketch].
// The scene never supplies a category or clue before the player asks for help.
export const WORDS = [
  ['APPLE', 'A crisp fruit often baked into pies.', 'An orchard in autumn.', 'orchard'],
  ['LEMON', 'A yellow citrus fruit with a sour taste.', 'A small squeeze can change a drink.', 'orchard'],
  ['CHERRY', 'A small stone fruit often sold in pairs on a stem.', 'Something red at the very top.', 'orchard'],
  ['PEACH', 'A soft, fuzzy fruit with a large stone inside.', 'Summer, with a velvet surface.', 'orchard'],
  ['COFFEE', 'A drink brewed from roasted beans.', 'Some mornings begin with a familiar smell.', 'cup'],
  ['TEAPOT', 'A vessel with a spout used to brew and pour tea.', 'A pause in the afternoon.', 'cup'],
  ['HONEY', 'The sweet food made by bees.', 'A little sweetness, carefully collected.', 'hive'],
  ['BREAD', 'A staple baked from dough, often sliced.', 'The kitchen smells warmer than usual.', 'oven'],
  ['COOKIE', 'A small sweet baked treat, sometimes with chocolate chips.', 'Something might be missing from the jar.', 'oven'],
  ['PIZZA', 'A baked round of dough topped with sauce and cheese.', 'Sharing can be measured in triangles.', 'oven'],
  ['GARDEN', 'A space where flowers or vegetables are grown.', 'Patience becomes something alive.', 'sprout'],
  ['FOREST', 'A large area covered with trees.', 'The path gets quieter and the shade gets deeper.', 'trees'],
  ['BLOSSOM', 'A flower on a tree or plant.', 'A brief sign that the season has turned.', 'sprout'],
  ['DESERT', 'A very dry region with little rainfall.', 'The horizon shimmers.', 'dunes'],
  ['ISLAND', 'Land surrounded by water.', 'Every direction eventually reaches a shore.', 'shore'],
  ['OCEAN', 'A vast body of salt water.', 'The horizon seems to have no end.', 'waves'],
  ['RIVER', 'A natural stream flowing toward another body of water.', 'Always on its way somewhere.', 'waves'],
  ['BRIDGE', 'A structure that carries a path over a gap.', 'Two sides finally meet.', 'crossing'],
  ['MOUNTAIN', 'A very high natural rise in the land.', 'The climb changes the view.', 'peaks'],
  ['VOLCANO', 'A mountain or opening that can release lava.', 'Something restless beneath the surface.', 'peaks'],
  ['THUNDER', 'The loud sound that follows lightning.', 'The sky has something to say.', 'storm'],
  ['RAINBOW', 'An arc of colors seen when sunlight meets rain.', 'The storm left something behind.', 'storm'],
  ['SNOWFLAKE', 'A single ice crystal that falls from a cloud.', 'Winter leaves a tiny signature.', 'snow'],
  ['BREEZE', 'A gentle, light wind.', 'You notice it without seeing it.', 'wind'],
  ['SHADOW', 'A dark shape made when something blocks light.', 'It follows without taking a step.', 'sun'],
  ['SUNRISE', 'The daily appearance of the sun above the horizon.', 'Another beginning.', 'sun'],
  ['CANDLE', 'A stick of wax with a wick that burns for light.', 'The room gets brighter as it gets smaller.', 'glow'],
  ['LANTERN', 'A portable lamp with a protective case.', 'A little company on a dark road.', 'glow'],
  ['MIRROR', 'A surface that reflects your image.', 'Someone copies every move you make.', 'reflection'],
  ['WINDOW', 'An opening with glass that lets light into a room.', 'A view without stepping outside.', 'reflection'],
  ['PILLOW', 'A soft support for your head in bed.', 'The day is finally over.', 'bed'],
  ['BLANKET', 'A large fabric covering used to keep warm.', 'A small defense against a cold night.', 'bed'],
  ['POCKET', 'A small pouch sewn into clothing.', 'Something useful is closer than you think.', 'pouch'],
  ['BUTTON', 'A small fastener passed through a hole in clothing.', 'A little detail holding things together.', 'pouch'],
  ['COMPASS', 'An instrument with a needle that points north.', 'Useful when every path looks alike.', 'trail'],
  ['JOURNEY', 'The act of traveling from one place to another.', 'The destination is only part of it.', 'trail'],
  ['ANCHOR', 'A heavy object used to keep a boat in place.', 'Sometimes staying matters more than moving.', 'boat'],
  ['SAILOR', 'A person who works or travels on a ship.', 'Home might be beyond the horizon.', 'boat'],
  ['BICYCLE', 'A two-wheeled vehicle powered by pedals.', 'Balance and a little effort.', 'wheel'],
  ['WAGON', 'A four-wheeled cart for carrying people or goods.', 'The load is easier when it rolls.', 'wheel'],
  ['ROCKET', 'A vehicle propelled by fast-moving exhaust, often into space.', 'Leaving the familiar far below.', 'stars'],
  ['PLANET', 'A large round body that orbits a star.', 'One traveler among many in the dark.', 'stars'],
  ['FEATHER', 'One of the light structures covering a bird.', 'Something left behind after flight.', 'flight'],
  ['BUTTERFLY', 'An insect with broad wings that develops from a caterpillar.', 'A very different second beginning.', 'flight'],
  ['DOLPHIN', 'An intelligent marine mammal with a curved dorsal fin.', 'A sudden leap beside the boat.', 'waves'],
  ['TURTLE', 'A reptile protected by a hard shell.', 'Carrying shelter wherever it goes.', 'shore'],
  ['VIOLIN', 'A small string instrument played with a bow under the chin.', 'A conversation without words.', 'music'],
  ['MELODY', 'A sequence of musical notes forming a tune.', 'Something you can carry in your head.', 'music'],
  ['LIBRARY', 'A place where books can be read or borrowed.', 'Many voices in a quiet room.', 'pages'],
  ['DIARY', 'A book used to record personal daily experiences.', 'A conversation with your future self.', 'pages'],
  ['PUZZLE', 'A problem or game solved by fitting clues or pieces together.', 'The pieces know something you do not yet.', 'pieces'],
  ['SECRET', 'Something deliberately kept from being known.', 'Not every closed door needs a key.', 'lock'],
  ['COURAGE', 'The ability to act despite fear.', 'Your knees can shake and you can still move.', 'steps'],
  ['PROMISE', 'A commitment to do or not do something.', 'Words that reach into tomorrow.', 'knot'],
  ['FRIEND', 'A person you know well and care about.', 'A familiar place beside you.', 'knot'],
  ['RESCUE', 'The act of saving someone from danger.', 'Someone is still reaching back.', 'steps'],
  ['CHAKRA', 'The energy a shinobi channels into techniques.', 'Something within, carefully directed.', 'glow'],
  ['HOKAGE', 'The title of the Hidden Leaf village leader.', 'A village looks to one person.', 'village'],
  ['KUNAI', 'A short pointed tool commonly carried by shinobi.', 'A small tool in a hidden pouch.', 'pouch'],
  ['SHURIKEN', 'A star-shaped throwing weapon used by shinobi.', 'A sharp answer sent from a distance.', 'spin'],
  ['RASENGAN', 'Naruto’s spinning sphere of chakra.', 'Power gathered into a turning center.', 'spin'],
  ['CHIDORI', 'A lightning technique named after a thousand birds.', 'A sharp sound before the strike.', 'storm'],
  ['SHARINGAN', 'The Uchiha clan’s distinctive eye ability.', 'Seeing a little more than everyone else.', 'reflection'],
  ['SENSEI', 'The title a student uses for a teacher in Japanese.', 'Someone once walked this path before you.', 'pages']
];

export const ABILITIES = {
  naruto: { name: 'Shadow clone', effect: 'Reveal one missing letter', kind: 'letter', line: 'My clone found a way through. There’s your letter!' },
  sasuke: { name: 'Sharingan', effect: 'Rule out three wrong letters', kind: 'eliminate', line: 'I can see the false marks. Ignore those letters.' },
  sakura: { name: 'Careful analysis', effect: 'Get a vague association', kind: 'association', line: 'I noticed something. Think about this connection.' },
  kakashi: { name: 'Ninken scout', effect: 'See a rough sketch', kind: 'sketch', line: 'Pakkun brought back a sketch. He’s a tracker, not an artist.' }
};
