import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { CROSSING_MODES, SKILLS, CrossingModel, district } from '../js/crossing-model.js';
import { CROSSING_STORAGE_KEY, loadCrossingRecords, recordCrossing } from '../js/crossing-records.js';

const modes = Object.values(CROSSING_MODES);
const advance = (game, seconds) => { for (let i = 0; i < Math.ceil(seconds * 120); i++) game.step(); };
function empty(mode) {
  const game = new CrossingModel(42, mode);
  for (const row of game.rows) { row.cars = []; row.obstacles = []; row.pickup = null; }
  game.begin(); return game;
}
function place(game, row, col = 3) {
  Object.assign(game.player, { x: col, y: row, prevX: col, prevY: row, col, row });
  game.furthest = row;
}

test('Easy preserves original release layouts, traffic, skill balance, and route length', () => {
  // Fingerprints from the released pre-difficulty model, not generated by this implementation.
  const original = { 0: 'f37559a815f8802560b08dc0e6bbe93697f5bf10341b802fbbcf775a457e266c',
    42: '440b2eeafb335bba063188153c422528c95098f5c764f87e932aa8262b4d3046',
    2026: '88eeb533a4f3f7f76d37676c9271d5efcf699d1fcaac11d877e5ae9041939796' };
  for (const [seed, hash] of Object.entries(original)) {
    const game = new CrossingModel(Number(seed), 'easy');
    assert.equal(createHash('sha256').update(JSON.stringify(game.rows)).digest('hex'), hash);
    assert.deepEqual(game.skillSettings, SKILLS);
    assert.equal(game.finish, 60);
  }
});

test('longer modes provide safe starts, district arrivals, final portals, and traversable traffic gaps', () => {
  for (const mode of modes) for (let seed = 0; seed < 20; seed++) {
    const game = new CrossingModel(seed, mode.id);
    assert.equal(game.rows.length, mode.finish + 1);
    const third = mode.finish / 3;
    for (const index of [0, 1, third, third + 1, third * 2, third * 2 + 1, mode.finish]) {
      assert.notEqual(game.rows[index].type, 'road');
      assert.equal(game.rows[index].obstacles.length, 0);
    }
    let roadStreak = 0;
    for (const row of game.rows) {
      roadStreak = row.type === 'road' ? roadStreak + 1 : 0;
      assert.ok(roadStreak < Math.max(...mode.roadPeriods));
      assert.ok(row.obstacles.length <= 3, 'Every safe island keeps at least four open columns.');
      for (const car of row.cars) assert.ok(row.cycle / row.cars.length - car.length > 1.8, 'A long vehicle still leaves a usable gap.');
      if (row.pickup) assert.ok(!row.obstacles.some(item => item.col === row.pickup.col));
    }
    assert.equal(district(third - 1, game.finish), 'Midtown');
    assert.equal(district(third, game.finish), 'Bryant Park');
    assert.equal(district(third * 2, game.finish), 'East River');
  }
});

test('successive modes measurably increase road speed, occupancy, uninterrupted road length, and scarcity', () => {
  let previous = null;
  for (const mode of modes) {
    let roads = 0, speed = 0, occupancy = 0, longest = 0;
    for (let seed = 0; seed < 12; seed++) {
      const game = new CrossingModel(seed, mode.id); let streak = 0;
      for (const row of game.rows) {
        if (row.type !== 'road') { streak = 0; continue; }
        longest = Math.max(longest, ++streak); roads++;
        speed += Math.abs(row.speed);
        occupancy += row.cars.reduce((total, car) => total + car.length, 0) / row.cycle;
      }
    }
    const current = { speed: speed / roads, occupancy: occupancy / roads, longest, ...mode };
    if (previous) {
      assert.ok(current.speed > previous.speed);
      assert.ok(current.occupancy > previous.occupancy);
      assert.ok(current.longest > previous.longest);
      assert.ok(current.laneEnergy < previous.laneEnergy);
      assert.ok(current.crystalEnergy < previous.crystalEnergy);
    }
    previous = current;
  }
});

test('every mode applies its own economy once per lane, crystal, and district, with exact fractional income', () => {
  for (const mode of modes) {
    const game = empty(mode.id); game.energy = 0;
    game.rows[1].pickup = { col: 3, taken: false };
    game.hop(0, 1); advance(game, 0.2);
    assert.equal(game.energy, mode.laneEnergy + mode.crystalEnergy);
    game.hop(0, -1); advance(game, 0.2); game.hop(0, 1); advance(game, 0.2);
    assert.equal(game.energy, mode.laneEnergy + mode.crystalEnergy);
    game.energy = 0; place(game, mode.finish / 3 - 1);
    game.hop(0, 1); advance(game, 0.2);
    assert.equal(game.energy, mode.laneEnergy + mode.districtEnergy);
    game.energy = 0; place(game, 1);
    for (let i = 0; i < 10; i++) { game.hop(0, 1); advance(game, 0.2); }
    assert.equal(game.energy, mode.laneEnergy * 10);
    advance(game, 60); assert.equal(game.energy, mode.laneEnergy * 10);
  }
});

test('higher modes charge more and recharge longer for every skill, retaining power duration and opening access', () => {
  for (const key of Object.keys(SKILLS)) {
    let lastCost = 0, lastWait = 0;
    for (const mode of modes) {
      const game = empty(mode.id), setting = game.skillSettings[key];
      assert.ok(setting.cost > lastCost && setting.cooldown > lastWait);
      assert.equal(setting.duration, SKILLS[key].duration);
      assert.equal(game.cast(key), true, 'Every skill can be chosen with the starting reserve.');
      assert.equal(game.energy, 100 - setting.cost);
      assert.equal(game.skills[key].cooldown, setting.cooldown);
      const energy = game.energy;
      assert.equal(game.cast(key), false); assert.equal(game.energy, energy);
      advance(game, setting.cooldown + 0.1);
      assert.equal(game.energy, energy, 'Cooldown recovery grants no magicules.');
      if (energy < setting.cost) assert.equal(game.cast(key), false);
      else assert.equal(game.cast(key), true);
      lastCost = setting.cost; lastWait = setting.cooldown;
    }
  }
});

test('extended routes pass lane 60, forecast their real boundary, and win only at their own portal', () => {
  for (const mode of modes.slice(1)) {
    const game = empty(mode.id); place(game, 59);
    game.hop(0, 1); advance(game, 0.2);
    assert.equal(game.phase, 'playing');
    assert.equal(game.forecast(0, 1), 'clear');
    game.hop(0, 1); advance(game, 0.2); assert.equal(game.player.row, 61);
    place(game, mode.finish - 1, 2);
    game.hop(0, 1); advance(game, 0.2); assert.equal(game.phase, 'playing');
    assert.equal(game.forecast(0, 1), 'blocked');
    game.hop(1, 0); advance(game, 0.2); assert.equal(game.phase, 'won');
    assert.equal(game.furthest, mode.finish);
  }
});

test('variable traffic cycles wrap offscreen, never through the player or into overlapping headways', () => {
  for (const mode of modes) for (const direction of [-1, 1]) {
    const game = empty(mode.id); place(game, 2);
    const row = game.rows[2]; row.speed = direction * 2;
    const vehicle = { x: direction > 0 ? row.cycle - 7 - 0.005 : -6.995, prevX: 0, length: 2.3, kind: 'truck', removed: true };
    row.cars = [vehicle]; game.step();
    assert.equal(game.phase, 'playing'); assert.equal(vehicle.removed, false);
    assert.equal(vehicle.prevX, vehicle.x);
    assert.ok(vehicle.x < -6 || vehicle.x > 10);
  }
});

test('retry keeps its difficulty and seed; switching mode resets only the requested run', () => {
  const game = new CrossingModel(91, 'hard');
  const streets = JSON.stringify(game.rows);
  game.begin(); game.cast('beelzebub'); game.hop(0, 1); advance(game, 0.2); game.reset();
  assert.equal(game.mode.id, 'hard'); assert.equal(game.seed, 91);
  assert.equal(JSON.stringify(game.rows), streets);
  assert.equal(game.energy, 100); assert.equal(game.skills.beelzebub.cooldown, 0);
  game.reset(92, 'demon'); assert.equal(game.finish, 300);
  game.reset(93, 'constructor'); assert.equal(game.mode.id, 'easy');
});

test('existing records migrate to Easy, and corrupt or unavailable storage still yields playable defaults', () => {
  const legacy = JSON.stringify({ best: 60, fastest: 73.5, sound: true });
  const migrated = loadCrossingRecords(key => key.endsWith('.v1') ? legacy : null);
  assert.deepEqual(migrated.modes.easy, { best: 60, fastest: 73.5 });
  assert.deepEqual(migrated.modes.demon, { best: 0, fastest: 0 });
  assert.equal(migrated.selectedMode, 'easy'); assert.equal(migrated.sound, true);
  const corrupt = loadCrossingRecords(key => key === CROSSING_STORAGE_KEY ? '{broken' : legacy);
  assert.deepEqual(corrupt, migrated);
  const denied = loadCrossingRecords(() => { throw new Error('denied'); });
  assert.equal(denied.modes.easy.best, 0);
  const invalid = loadCrossingRecords(() => JSON.stringify({ selectedMode: 'toString', modes: { hard: { best: 999, fastest: -3 } } }));
  assert.equal(invalid.selectedMode, 'easy'); assert.deepEqual(invalid.modes.hard, { best: 0, fastest: 0 });
});

test('distance and completion records remain independent and survive saving/loading each difficulty', () => {
  const record = loadCrossingRecords(() => null);
  for (const mode of modes) {
    const game = empty(mode.id); game.furthest = mode.finish; game.elapsed = mode.finish / 2; game.phase = 'won';
    assert.equal(recordCrossing(record, game), true);
    assert.equal(recordCrossing(record, game), false);
  }
  record.selectedMode = 'demon';
  const loaded = loadCrossingRecords(key => key === CROSSING_STORAGE_KEY ? JSON.stringify(record) : null);
  assert.deepEqual(loaded, record);
  const easy = empty('easy'); easy.furthest = 12; easy.elapsed = 1;
  assert.equal(recordCrossing(loaded, easy), false);
  assert.equal(loaded.modes.easy.fastest, 30);
  assert.equal(loaded.modes.demon.fastest, 150);
});
