import test from 'node:test';
import assert from 'node:assert/strict';
import { HunterModel, options, loadout, loadRecords, remember, recordKey, CHARACTERS, COURSES, DIFFICULTIES } from '../js/hunter-model.js';
import { createLevel } from '../js/hunter-levels.js';
import { pilot } from './hunter-pilot.mjs';
const advance=(m,s)=>{for(let i=0;i<Math.round(s*120);i++)m.step();};
function open(config){const m=new HunterModel(7,config);m.begin();return m;}
function empty(config){const m=open(config);m.level.platforms=[{id:0,x:0,y:310,w:1100,h:90,kind:'stone'}];m.level.hazards=[];m.level.gems=[];m.level.guard=null;return m;}
test('Nothing auto-runs; timer starts with input; movement brakes and reverses',()=>{const m=empty();advance(m,2);assert.equal(m.p.x,65);assert.equal(m.remaining,120);m.setInput('right',true);advance(m,.4);assert.ok(m.p.x>135);m.setInput('right',false);advance(m,.2);assert.equal(m.p.vx,0);const x=m.p.x;m.setInput('left',true);advance(m,.3);assert.ok(m.p.x<x-40);assert.equal(m.p.facing,-1);assert.ok(m.remaining<120);});
test('Holding jump gives a higher arc than tapping; horizontal air control works',()=>{function apex(release){const m=empty();m.jump();let min=310;for(let i=0;i<110;i++){if(i===release)m.releaseJump();m.step();min=Math.min(min,m.p.y);}return min;}assert.ok(apex(100)<210);assert.ok(apex(5)>240);const m=empty();m.jump();m.setInput('right',true);advance(m,.2);m.setInput('right',false);m.setInput('left',true);advance(m,.2);assert.ok(m.p.vx<0);});
test('Solid walls stop horizontal motion; thin ledges can be jumped through from below',()=>{const m=empty();m.level.platforms.push({id:1,x:150,y:200,w:80,h:110,kind:'stone'});m.setInput('right',true);advance(m,1);assert.equal(m.p.x,139);const n=empty();n.level.platforms.push({id:1,x:20,y:245,w:150,h:22,kind:'stone'});n.jump();advance(n,.65);assert.equal(n.p.y,245);assert.equal(n.p.grounded,true);});
test('Coyote time permits a jump just after walking off an edge',()=>{const m=empty();m.level.platforms[0].w=140;m.setInput('right',true);while(m.p.grounded)m.step();advance(m,.04);m.jump();m.step();assert.ok(m.p.vy<0);});
test('Buffered jump fires on landing without holding an auto-jump loop',()=>{const m=empty();m.jump();advance(m,.65);m.releaseJump();m.jump();advance(m,.13);assert.ok(m.p.vy<0);advance(m,1);assert.equal(m.p.y,310);});
test('Checkpoints restore position, preserve collected badges, and cost the stated time',()=>{const m=empty();m.level.checkpoint={x:80,y:310,active:false};m.setInput('right',true);advance(m,.1);m.setInput('right',false);advance(m,.1);assert.equal(m.level.checkpoint.active,true);m.badges=2;const t=m.remaining;m.die();advance(m,.36);assert.equal(m.p.x,80);assert.equal(m.badges,2);assert.equal(m.deaths,1);assert.ok(m.remaining<=t-2);assert.ok(m.remaining>t-2.5);});
test('Moving platforms carry the player and cracked platforms collapse and recover',()=>{const m=empty();m.level.platforms=[{id:0,x:0,baseX:0,previousX:0,y:310,w:200,h:22,kind:'moving'}];const x=m.p.x;advance(m,.5);assert.ok(m.p.x>x+10);const n=empty();n.level.platforms[0].kind='crumble';n.level.platforms[0].crumble=-1;n.level.platforms[0].broken=0;advance(n,.72);assert.ok(n.level.platforms[0].broken>0);assert.equal(n.p.grounded,false);});
test('All 36 Trial combinations complete the six authored rooms without powers',()=>{for(const character of Object.keys(CHARACTERS))for(const course of Object.keys(COURSES))for(const difficulty of Object.keys(DIFFICULTIES)){const m=open({character,course,difficulty});let steps=0;while(['playing','transition'].includes(m.phase)&&steps++<16000)pilot(m);assert.equal(m.phase,'won',`${character}/${course}/${difficulty}`);assert.equal(m.cleared,6);assert.equal(m.deaths,0);assert.ok(m.remaining>0);}});
test('Endless advances beyond all course rooms with bounded level data and capped time',()=>{const m=open({mode:'endless',course:'yorknew'});let steps=0;while(m.cleared<40&&['playing','transition'].includes(m.phase)&&steps++<40000)pilot(m);assert.ok(m.cleared>=40);assert.notEqual(m.phase,'won');assert.ok(m.level.platforms.length<15);assert.ok(m.remaining<=120);});
test('Pause clears held input and freezes every game clock',()=>{const m=open();m.setInput('right',true);advance(m,.2);m.pause();const s=[m.p.x,m.remaining,m.clock,m.elapsed];advance(m,4);assert.deepEqual([m.p.x,m.remaining,m.clock,m.elapsed],s);m.resume();assert.equal(m.input.right,false);});
test('Timer expiry ends the attempt and retry resets the whole course',()=>{const m=open();m.started=true;m.remaining=.1;advance(m,.2);assert.equal(m.phase,'over');m.reset();assert.equal(m.phase,'ready');assert.equal(m.cleared,0);assert.equal(m.remaining,120);});
test('Powers require a real target and keep pre-Nen kits era-appropriate',()=>{assert.equal(loadout({character:'gon'}).skill,'rod');assert.equal(loadout({character:'killua',mode:'endless'}).skill,'godspeed');assert.equal(loadout({character:'kurapika'}).skill,'blades');const m=empty({character:'gon'});assert.equal(m.cast(),false);assert.equal(m.energy,100);m.level.gems=[{x:130,y:270,taken:false}];assert.equal(m.cast(),true);assert.equal(m.badges,1);assert.equal(m.energy,75);});
test('Jajanken charges before breaking a crate; gum applies a physical aerial impulse',()=>{const m=empty({character:'gon',course:'greed'});const b={id:1,x:100,y:278,w:32,h:32,kind:'crate'};m.level.platforms.push(b);assert.equal(m.cast(),true);assert.equal(b.removed,undefined);advance(m,.4);assert.equal(b.removed,true);const h=empty({character:'hisoka'});h.level.anchors=[{x:150,y:190}];assert.equal(h.cast(),true);assert.ok(h.p.vx>0);assert.ok(h.p.vy<0);advance(h,.1);assert.ok(h.p.y<270);});
test('Electrical skills spend finite charge; entering the next room supplies charge',()=>{const m=empty({character:'killua',mode:'endless'});assert.equal(m.cast(),true);const e=m.energy;advance(m,2);assert.equal(m.energy,e);m.loadRoom(1);assert.equal(m.energy,Math.min(100,e+30));});
test('Every authored room has reachable checkpoint ground and an exit surface',()=>{for(const course of Object.keys(COURSES))for(let i=0;i<6;i++){const l=createLevel(course,i);for(const flag of [l.checkpoint,l.goal])assert.ok(l.platforms.some(b=>flag.x>=b.x&&flag.x<=b.x+b.w&&flag.y===b.y));assert.ok(l.platforms.length>=4);}});
test('Corrupt storage is safe and records separate characters, modes, courses and challenges',()=>{assert.equal(options({character:'__proto__'}).character,'killua');assert.equal(loadRecords(()=>'{').selection.mode,'trial');const r=loadRecords(()=>null),m=open();m.cleared=3;m.badges=2;remember(r,m);assert.equal(r.scores[recordKey(m.config)].rooms,3);assert.equal(r.scores[recordKey({...m.config,mode:'endless'})],undefined);});
